name: Mirror Pantheon -> GitHub

on:
  workflow_dispatch:
    inputs:
      allow_deletions:
        description: 'Allow remote deletions (use with caution). Set to "true" to enable exact mirror including deletions.'
        required: false
        default: 'false'

env:
  PANTHEON_GIT_URL: ${{ secrets.PANTHEON_GIT_URL }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Start ssh-agent and add PANTHEON key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PANTHEON_SSH_KEY }}

      - name: Add Pantheon host key to known_hosts (extract host/port from URL)
        run: |
          set -e
          mkdir -p ~/.ssh
          URL="${PANTHEON_GIT_URL}"
          NO_PROTO="${URL#ssh://}"
          NO_USER="${NO_PROTO#*@}"
          HOSTPORT="${NO_USER%%/*}"
          HOST="${HOSTPORT%%:*}"
          PORT="${HOSTPORT#*:}"
          if [ "$PORT" != "$HOSTPORT" ]; then
            ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts 2>/dev/null || ssh-keyscan "$HOST" >> ~/.ssh/known_hosts
          else
            ssh-keyscan "$HOST" >> ~/.ssh/known_hosts
          fi

      - name: Mirror clone Pantheon repository
        env:
          PANTHEON_GIT_URL: ${{ secrets.PANTHEON_GIT_URL }}
        run: |
          git clone --mirror "${PANTHEON_GIT_URL}" pantheon.git


      - name: Push to GitHub (conditional deletions)

      - name: Push branches and tags to GitHub (safe: no deletions)

        env:
          GH_REPO: ${{ github.repository }}
        run: |
          cd pantheon.git
          # set push URL (uses GITHUB_TOKEN)
          git remote set-url --push origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GH_REPO}.git"


          if [ "${{ github.event.inputs.allow_deletions }}" = "true" ]; then
            echo "allow_deletions is true -> performing git push --mirror origin"
            git push --mirror origin
          else
            echo "allow_deletions is not true -> performing safe push (no deletions)"
            git for-each-ref --format='%(refname:short)' refs/heads | \
              while read -r BR; do
                echo "Pushing branch: $BR"
                git push origin "refs/heads/$BR:refs/heads/$BR" || { echo "Failed to push branch $BR"; exit 1; }
              done
            git push origin --tags
          fi
          # Push each local branch explicitly to avoid any delete refspecs.
          # This pushes existing branches one by one (creates/updates on remote),
          # but does NOT delete remote branches that don't exist locally.
          git for-each-ref --format='%(refname:short)' refs/heads | \
            while read -r BR; do
              echo "Pushing branch: $BR"
              git push origin "refs/heads/$BR:refs/heads/$BR" || {
                echo "Failed to push branch $BR"
                exit 1
              }
            done

          # Push tags
          git push origin --tags
