name: Mirror Pantheon -> GitHub

on:
  workflow_dispatch:

env:
  PANTHEON_GIT_URL: ${{ secrets.PANTHEON_GIT_URL }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Start ssh-agent and add PANTHEON key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PANTHEON_SSH_KEY }}

      - name: Add Pantheon host key to known_hosts (extract host/port from URL)
        run: |
          set -e
          mkdir -p ~/.ssh
          URL="${PANTHEON_GIT_URL}"
          # remove protocol if present
          NO_PROTO="${URL#ssh://}"
          # remove user@ if present
          NO_USER="${NO_PROTO#*@}"
          # extract host:port or host/path
          HOSTPORT="${NO_USER%%/*}"
          HOST="${HOSTPORT%%:*}"
          PORT="${HOSTPORT#*:}"
          echo "Using host: $HOST${PORT:+ port: $PORT}"
          if [ "$PORT" != "$HOSTPORT" ]; then
            # try ssh-keyscan with port; if it fails, fallback to host only
            ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts 2>/dev/null || ssh-keyscan "$HOST" >> ~/.ssh/known_hosts
          else
            ssh-keyscan "$HOST" >> ~/.ssh/known_hosts
          fi
          echo "Known hosts entries:"
          cat ~/.ssh/known_hosts

      - name: Mirror clone Pantheon repository
        env:
          PANTHEON_GIT_URL: ${{ secrets.PANTHEON_GIT_URL }}
        run: |
          git clone --mirror "${PANTHEON_GIT_URL}" pantheon.git

      - name: Push mirror to GitHub
        env:
          GH_REPO: ${{ github.repository }}
        run: |
          cd pantheon.git
          git remote set-url --push origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GH_REPO}.git"
          git push --mirror origin